server:
  port: 9000
spring:
    thymeleaf:
          mode: LEGACYHTML5
          prefix: classpath:/templates/
          suffix: .html
    mvc:
      static-path-pattern: /**
    resources:
      static-locations: ["classpath:/templates/","classpath:/META-INF/resources/","classpath:/static/","classpath:/static/css"]
#    resources:
##      static-locations: file:/Users/gaara/Downloads/mp/
#      static-locations: file:/home/mp/
#    mvc:
#      static-path-pattern: /mp/**
#cas:
#  server-url-prefix: https://www.gaara-xu.com
#  server-login-url: https://cas.gaara-xu.com/cas/login
#  client-host-url: http://www.gaara-xu.com
##  client-host-url: http://118.24.182.136:9002
#  validation-type: cas
##mypath: /Users/gaara/Downloads/mp/
mypath: /home/mp/