server:
  port: 9002
spring:
    thymeleaf:
          mode: LEGACYHTML5
    resources:
#      static-locations: file:/Users/gaara/Downloads/mp/
      static-locations: file:/home/mp/
    mvc:
      static-path-pattern: /mp/**
cas:
  server-url-prefix: https://cas.gaara-xu.com
  server-login-url: https://cas.gaara-xu.com/cas/login
  client-host-url: http://118.24.182.136:9002
  validation-type: cas
#mypath: /Users/gaara/Downloads/mp/
mypath: /home/mp/